app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(IDCols = "ID")
app$setInputs(IDCols = c("ID", "Name"))
app$setInputs(y_variable = "Sex")
app$setInputs(x_variable = "PreinvasiveComponent")
app$setInputs(color_variable = "PNI")
app$setInputs(corr_mat_Cols = "ID")
app$setInputs(corr_mat_Cols = c("ID", "Name"))
app$setInputs(TP = "34")
app$setInputs(FP = "56")
app$setInputs(FN = "34")
app$setInputs(TN = "67")
app$setInputs(`id1-refresh` = "click")
app$setInputs(pivot2Cols = "ID")
app$setInputs(survfactor = "Sex")
app$setInputs(input_type = "c_diff")
app$setInputs(comment = "345")
app$setInputs(select_data_ui = "spss_ui")
app$uploadFile(uploaded_spss_file = "pancreas-data-to-combine.sav") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(spss_Button = "click")
app$setInputs(spss_Button = "click")
app$setInputs(spss_Button = "click")
app$setInputs(select_data_ui = "general_ui")
app$setInputs(readFunction = "read.spss")
app$uploadFile(file = "pancreas-data-to-combine.sav") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(readFunction = "read.delim2")
app$setInputs(readFunction = "read.spss")
app$setInputs(`read.spss__use.value.labels` = "")
app$uploadFile(uploaded_general_file = "pancreas-data-to-combine.sav") # <-- This should be the path to the file, relative to the app's tests/ directory
app$setInputs(general_Button = "click")
app$snapshot()
